name: Deploy CDK Stack

# Trigger the workflow on pushes to the main branch or any other branch you prefer
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (CDK uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install AWS CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2' 

      # Step 6: Deploy CDK stack
      - name: Deploy CDK stack
        run: cdk bootstrap aws://664418951913/eu-west-2

      # Step 6: Deploy CDK stack
      - name: Deploy CDK stack
        run: cdk deploy --require-approval never

